### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte in `clean` function

### ISSUE THREAD

**Issue by nicehiro** [n8henrie/pycookiecheat#18] opened 2017-08-22 03:19 UTC
Hi, @n8henrie , I found this error when I use `pycookiecheat` 

**my machine version info:** 
Linux version 4.9.43-1-MANJARO (builduser@manjaro) (gcc version 7.1.1 20170630 (GCC) ) #1 SMP PREEMPT Sun Aug 13 20:28:47 UTC 2017
**google-chrome version:**
60.0.3112.101 (Official Build) (64-bit)

here's my test code:
```python
import requests
from pycookiecheat import chrome_cookies


if __name__ == '__main__':
      url = 'https://www.google.com'
      cookies = chrome_cookies(url)
```
hers's traceback:
```
➜  crawer git:(master) ✗ python pycookietest.py 
Traceback (most recent call last):
  File "pycookietest.py", line 7, in <module>
    cookies = chrome_cookies(url)
  File "/usr/lib/python3.6/site-packages/pycookiecheat/pycookiecheat.py", line 216, in chrome_cookies
    init_vector=config['init_vector'])
  File "/usr/lib/python3.6/site-packages/pycookiecheat/pycookiecheat.py", line 64, in chrome_decrypt
    return clean(decrypted)
  File "/usr/lib/python3.6/site-packages/pycookiecheat/pycookiecheat.py", line 41, in clean
    return decrypted[:-last].decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 0: invalid start byte
```
And I also research the issue https://github.com/n8henrie/pycookiecheat/issues/12
I was wondering if the value of `my_pass` is wrong, so I print every detail in decrypt process
here's return:
```
encrypted_value:  b'v11\n?r\xec\xcb\x8f\x8f\x1c\x08\x05A 8\xec\x81N~7\xc1O\xa0\xc0\xdd\xbb\xfb\xaa=\xfb\x90\xbd\x1f$'
unlocked_keyring:  []
my_pass:  peanuts
decrypted_value:  b's\t\xdd\xf6mp\x97\x12v\xcf\xd7\x9b\x1c\x83\xf5;\xdd\xa1\xf5\xf5\xe0!S\xb9\xa4\x85C\xbc\xb4\x8b\x93A'
clean_decrypted_value:  
```
**unlocked_keyring was got from your code**
**clean_decrypted_value is ues clean() function** got.
Some clean_decrypted_value is None, some are runs faild, and got the same log `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 0: invalid start byte`.

Please help me figure this out. Thanks!

BTW, forgive my poor English...

**Comment by n8henrie** [comment] 2017-08-26 20:42
Huh. What does this output?

```bash
python3 -c 'import sys; print(sys.getdefaultencoding())'
```

**Comment by nicehiro** [comment] 2017-08-26 22:51
@n8henrie The output is 'utf-8'.

**Comment by n8henrie** [comment] 2017-08-28 04:05
Huh, well that's not the problem.

I'm having a hard time reproducing the issue -- I've tested with on Chrome 60 on MacOS 10.12.6 and Ubuntu 16.04, worked fine on both.

> I was wondering if the value of my_pass is wrong
What do you mean by this?

**Comment by nicehiro** [comment] 2017-08-28 10:09
I'm sorry to waste you a lot of time and I'm so happy you can help me solve the problem. 

My system is based on arch, in your code my_pass is peanuts, perhaps in my system my_pass is not peanuts, nor is it similar to ubuntu's my_pass.

**Comment by n8henrie** [comment] 2017-08-28 17:32
No trouble, hopefully we'll figure it out.

I have a few devices running Arch -- I was able to use pycookiecheat with
Chromium 60 on one of them this morning, also no issues there. Can you try
Chromium and let me know if you see different behavior vs Chrome?

**Comment by nicehiro** [comment] 2017-08-29 02:22
I tried to use chromium, and I got the same fault. This is so wierd.

Can you tell me your my_pass on arch? Is that ‘peanuts’? Maybe my system lacks some dependencies?

**Comment by n8henrie** [comment] 2017-09-07 13:44
Yes, I left the default my_pass as far as I can recall. Will try to double check soon.

**Comment by n8henrie** [comment] 2017-09-08 22:15
Yes, still `peanuts`.

**Comment by n8henrie** [comment] 2017-09-08 22:23
What desktop environment are you using? Do you have some kind of keyring (e.g. `gnome-keyring`) that may be messing with things?

**Comment by nicehiro** [comment] 2017-09-10 13:34
@n8henrie Finally can decrypt. I reinstall the system and change another desktop xfce, (old desktop is kde). Sorry I don't know how to get the keyring in kde.

Thank you again!

**Comment by n8henrie** [comment] 2017-09-10 14:06
Huh, well I'll have to look into KDE and see if there is a default keyring. For the moment feel free to close this issue, glad you got it working.

**Comment by n8henrie** [comment] 2017-09-26 12:39
Just got another report of this by email.

**Comment by n8henrie** [comment] 2017-10-21 03:52
Okay, closing due to inactivity. If anyone using KDE wants to try to replicate, I'd appreciate it.

**Comment by AlpNek** [comment] 2018-02-06 03:40
I still get this error on Arch (Netrunner) + KDE 5.12.x. Tried with python2 and python3.

**Comment by n8henrie** [comment] 2018-02-10 01:15
Are you also getting it with `0xbe`?

**Comment by Lucky0711** [comment] 2018-06-23 18:57
I am getting this as well, same spot but with slightly different byte and message:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 0: invalid continuation byte

Running Linux Mint 18 Sarah 64 bit, Kernal Linux 4.4.0-116-generic x86_64
MATE 1.14.1

Chrome Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by n8henrie** [comment] 2018-06-27 15:13
This will be tough for me to debug.

Can you give me the output for `python3 -c 'import sys; print(sys.getdefaultencoding())'` as per above?

Also, what is your default encoding in Chrome?

Find the `Cookies` file for Chrome / Chromium, and run the following:

```shellcommand
$ cp Cookies{,.bak}
$ sqlite3 Cookies.bak 'PRAGMA encoding;'
```

**Comment by Lucky0711** [comment] 2018-06-28 23:35
Sure - the output is:utf-8
The output of the Cookies is:UTF-8
Could it be they are a different case?    On Wednesday, June 27, 2018, 10:13:12 AM CDT, Nathan Henrie <notifications@github.com> wrote:  
 
 
This will be tough for me to debug.

Can you give me the output for python3 -c 'import sys; print(sys.getdefaultencoding())' as per above?

Also, what is your default encoding in Chrome?

Find the Cookies file for Chrome / Chromium, and run the following:
$ cp Cookies{,.bak}
$ sqlite3 Cookies.bak 'PRAGMA encoding;'

**Comment by n8henrie** [comment] 2018-07-06 19:40
Bump @Lucky0711

**Comment by Lucky0711** [comment] 2018-07-07 19:33
Hi sorry - was out of town for the past week.  How do I get that value?

**Comment by n8henrie** [comment] 2018-07-07 22:40
No worries.

I would recommend using [`pdb`](https://docs.python.org/3/library/pdb.html), the built-in python debugger.

For example, I think you could probably write a script like this that provokes a crash:

```python
from pycookiecheat import chrome_cookies
cookies = chrome_cookies('https://n8henrie.com')
print(cookies)
```

Name it something like `test.py`.

Run it to make sure it provokes the exception you noted above: `python3 test.py`. If it doesn't, change it to make whatever you were doing above so that it raises the exception.

Once you know it crashes, try running it in the debugger using `continue`, which will run until either a breakpoint or until an uncaught exception. You can either:

1. Run `python3 -m pdb test.py`, which will start the debugger interactively, and then type `c`, or 
2. Run `python3 -m pdb test.py -c continue` which already tells it to `c` from the get-go.

Once you can see the traceback before the `(Pdb)` prompt, you should be able to poke around things, for example `p decrypted` and likely `p encrypted_value`. Pdb's built-in `help` is good.

**Comment by n8henrie** [comment] 2018-09-07 17:40
It seems like this issue was resolved over email by unclear means through the commits on 7/6/18.

**Closed by n8henrie** 2018-09-07 17:40 UTC
Labels: awaiting_response, bug

**Comment by ikhmyz** [comment] 2019-01-17 19:57
Had the same issue, the next solution helped:

```
import secretstorage

bus = secretstorage.dbus_init()
collection = secretstorage.get_default_collection(bus)
for item in collection.get_all_items():
    if item.get_label() == 'Chrome Safe Storage':
        MY_PASS = item.get_secret()
        break
else:
    raise Exception('Chrome password not found!')
```

found here [https://stackoverflow.com/a/44808566](https://stackoverflow.com/a/44808566)

**Comment by f3anaro** [comment] 2021-08-31 08:15
I was experiencing the same issue. It turned out that the problem was that `pycookiecheat` was running in a virtualenv with no access to the system-level `gi` package. `pycookiecheat` fails silently if the package is not found.

Some solutions to this problem:

1. Create the virtualenv with `--system-site-packages`
2. Install [PyGObject](https://pygobject.readthedocs.io/) in the virtualenv: `pip install PyGObject` (requires some build dependencies)
3. Symlinks the system sites-package into the virtualenv
4. Use [vext](https://github.com/vext-python/vext): `pip install vext.gi`
